#!/bin/bash

#Lillian Tatka
#1/26/2022

# Check for minimum number of args
if [ $# -lt 2 ]; then
  echo "Usage: combine outputfilename [inputfilename...]" 1>&2; exit 1
fi

# Check if output file exists
if [ -e "$1" ]; then
  echo "Error: Output file should not exist" 1>&2; exit 1
fi

FILE_OUT="$1"

# Adjust indices 
shift

# Get contents of each input file and write them to the output file
cat "$@" > "$FILE_OUT" 2>&1

exit 0

 
