#!/bin/bash

# arg1: output filename
# arg2: input filename

# Check for correct number of args:
if [ $# -ne 2 ]; then
  echo Error: incorrect number of arguments - 2 required.; exit 1
fi

# Check that input file exists:
if [ ! -e "$0" ]; then
  echo "$0" does not exist.; exit 1
fi

# Check if output file exists and overwrite:
if [ -e "$1" ]; then
  echo The file "$1" already exists. Overwriting...
  rm "$1"
fi

touch "$1"

# Find URLs and remove surrounding text
grep http://courses.cs courses-index.html | sed 's/^.*http/http/g'| grep -o 'http:\/\/courses.cs.washington.edu\/courses\/cse[a-zA-Z0-9]*'| uniq | sort  >> "$1"

exit 0


